// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FunShareWebApi.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public string ProductIntro { get; set; }

    public int SupplierId { get; set; }

    public int? AgeId { get; set; }

    public int? Level { get; set; }

    public int? Stock { get; set; }

    public DateTime? ReleasedTime { get; set; }

    public int? Times { get; set; }

    public int? IntervalId { get; set; }

    public string Note { get; set; }

    public int StatusId { get; set; }

    public bool IsClass { get; set; }

    public double? Commision { get; set; }

    public string Features { get; set; }

    public virtual ICollection<ImageList> ImageList { get; set; } = new List<ImageList>();

    public virtual ICollection<ProductDetail> ProductDetail { get; set; } = new List<ProductDetail>();

    public virtual Supplier Supplier { get; set; }
}